### ISSUE TITLE
Mounts result in duplicate space for all seeding torrents and IO intensive imports

### ISSUE THREAD

**Issue by bakerboy448** [GenericEric/genericmediafactory#9]
https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/

Mounts of `/downloads` etc. should not be used

> The default path setup suggested by some docker developers that encourages people to use mounts like /movies, /tv, /books or /downloads is very suboptimal and it makes them look like two or three file systems, even if they aren’t (Because of how Docker’s volumes work). It is the easiest way to get started. While easy to use, it has a major drawback. Mainly losing the ability to hardlink or instant move, resulting in a slower and more I/O intensive copy + delete is used.

**Comment by GenericEric** [comment]
Subdirectories are not supported by Sab, so will leave the defaults as is. It can be changed by anyone using the charts.

**Comment by GenericEric** [comment]
Subdirectories are not supported by Sab, so will leave the defaults as is. It can be changed by anyone using the charts.

**Comment by bakerboy448** [comment]
> Subdirectories are not supported by Sab, so will leave the defaults as is. It can be changed by anyone using the charts.

Explain....how so?

sab has no restrictions on a mount like /data/downloads/usenet:/data/downloads/usenet and configuring categories / incomplete folders to use relative or absolute paths

**Comment by thezoggy** [comment]
> Subdirectories are not supported by Sab, so will leave the defaults as is. It can be changed by anyone using the charts.

Sub dirs are fine. You just can't put incomplete inside complete folder. Sab will check and warn about it.
